server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG


spring:
  application:
    name: twitter-to-kafka-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TanayaKarmakar/twitter-to-kafka-config-repo
          clone-on-start: true
          search-paths: {application}
          default-label: main
      fail-fast: true