spring:
  application:
    name: elastic-query-service
  profiles:
    active: elastic_query
  cloud:
    config:
      name: elastic-query-service,config-client
      uri: http://localhost:8888

server:
  port: 8084
  servlet:
    context-path: /elastic-query-service

elastic-query-config:
  text-field: text


elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connection-timeout-ms: 5000
  socket-timeout-ms: 30000